//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shopbdEntities : DbContext
    {
        private static shopbdEntities _context;

        public static shopbdEntities GetContext()
        {
            if (_context == null) _context = new shopbdEntities();
            return _context;
        }
        public shopbdEntities()
            : base("name=shopbdEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<ProductTypes> ProductTypes { get; set; }
        public virtual DbSet<sales> sales { get; set; }
        public virtual DbSet<suppliers> suppliers { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
