//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int id { get; set; }
        public int typeid { get; set; }
        public string name { get; set; }
        public int weight { get; set; }
        public int purchasePrice { get; set; }
        public int salePrice { get; set; }
        public int suppliersid { get; set; }
        public int quantity { get; set; }
        public byte[] img { get; set; }
    
        public virtual ProductTypes ProductTypes { get; set; }
        public virtual suppliers suppliers { get; set; }
    }
}
