//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        public int id { get; set; }
        public int userid { get; set; }
        public System.DateTime datetime { get; set; }
        public int price { get; set; }
        public string allproducts { get; set; }
        public string status { get; set; }
    
        public virtual users users { get; set; }
    }
}
